--19.Casos tamizados por Departamento, mes y sexo
SELECT COUNT(T.CANTIDAD) AS CANTIDAD,DO.DESCRIPCION, T.Sexo, MONTH(T.Fecha) AS MES
FROM CASOS_T T INNER JOIN MUNICIPIO MO ON T.ID_MUNICIPIO = MO.ID_MUNICIPIO 
INNER JOIN DEPARTAMENTO DO ON MO.ID_DEPARTAMENTO = DO.ID_DEPARTAMENTO WHERE T.Sexo IS NOT NULL
GROUP BY T.CANTIDAD,T.Sexo,DO.DESCRIPCION,MONTH(Fecha) ORDER BY MONTH(Fecha) ASC